version: "3.3"

networks:
  default:
    external:
      name: qwerty

services:

  qdrant:
    image: registry.cn-hangzhou.aliyuncs.com/huangyalong/qdrant:v1.15.5
    container_name: project-qdrant
    privileged: true
    ports:
      - "3233:6333"
      - "3234:6334"
    environment:
      - "TZ=Asia/Shanghai"
    volumes:
      - "$PWD/snapshots:/qdrant/snapshots"
      - "$PWD/data:/qdrant/storage"
    restart: unless-stopped
